### ISSUE TITLE
2.4: Update docs for release

### ISSUE THREAD

**Issue by degville** [CanonicalLtd/maas-docs#857]
- [ ] #856 top-level navigation changes 2.4 5
- [ ] #855 KVM over-commit ratios for CPU and memory
- [ ] #854  maas-dns package deprecated
- [ ] #853 ntpd deprecated, NTP services provided by Chrony
- [ ] #852 web UI screenshot refresh 2.4 13
- [ ] #851 top-level What's New in 2.4 doc
- [ ] #850 Add details on Machine Locking 
- [ ] #849 Remove references to deprecated Apache
- [ ] #848 Add upgrade PostgreSQL doc to toc
- [ ] #847 `maas init --mode all` no longer an option
- [ ] #846 New options when commissioning a machine
